### ISSUE TITLE
Add names of symbols

### ISSUE THREAD

**Issue by lrettig** [benjaminion/YellowPaper_CheatSheet#1]
Hello,

Thanks for creating this, it's very helpful. I don't know the names of many of these Greek letters, which makes it very hard to read these out loud (or in my head). Could this be added?

E.g.: ![image](https://user-images.githubusercontent.com/3316532/48362170-0a1a7880-e671-11e8-8e8d-fb40290cff2e.png)

**Comment by veox** [comment]
For now, cheat-sheet:

* [greek alphabet at Wikipedia](https://en.wikipedia.org/wiki/Greek_alphabet#Letters) - pronunciation on-screen;
* [greek alphabet at RapidTables](https://www.rapidtables.com/math/symbols/greek_alphabet.html#) - pronunciation as sound samples, and a font more closely matching that used in the YP.

**Comment by behradkhodayar** [comment]
> Hello,
> 
> Thanks for creating this, it's very helpful. I don't know the names of many of these Greek letters, which makes it very hard to read these out loud (or in my head). Could this be added?
> 
> E.g.: ![image](https://user-images.githubusercontent.com/3316532/48362170-0a1a7880-e671-11e8-8e8d-fb40290cff2e.png)

I understand the difficulty of reading such paper, but if you wanna be inclusive this far, maybe some other reader even asks for including a phonetics guide in the paper, which obviously doesn't sound rational.
Please refer to @veox's comment (2nd link, though not sure about /iota/'s pronunciation. other chars are fine).

Maybe time to close this issue.
